### ISSUE TITLE
[UI] Annotation toolbar should be above image

### ISSUE THREAD

**Issue by charlesh88** [topcoderinc/openmct#11]
Deliver 10-10-17

The annotation toolbar should be placed at the top of the dialog's workspace, per Notebook UI v1.0.3 page 135.
![screen shot 2017-10-11 at 11 25 18 am](https://user-images.githubusercontent.com/1056412/31459105-01787408-ae77-11e7-96d1-42b6858d8110.png)

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
Toolbar moved to top area
![screenshot 2017-10-16 12 30 07](https://user-images.githubusercontent.com/4476442/31596622-dafcaa74-b26d-11e7-8cc4-22ed254bddba.png)

**Comment by charlesh88** [comment]
Reviewed 10-18-17. Accepted.
