### ISSUE TITLE
[UI] Annotation toolbar scroll hides controls

### ISSUE THREAD

**Issue by charlesh88** [topcoderinc/openmct#12]
Delivery 10-10-17

The placement of the annotation toolbar in the markup ends up hiding controls for certain tool types, like text, making them unusable. Moving the toolbar out of the scrolling region will fix this.
![screen shot 2017-10-11 at 11 27 55 am](https://user-images.githubusercontent.com/1056412/31459324-ac376b7e-ae77-11e7-986d-abcc64eecaff.png)

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
This is fixed now
![screenshot 2017-10-16 12 30 07](https://user-images.githubusercontent.com/4476442/31596608-c6fca326-b26d-11e7-94c8-360d597a8ff2.png)

**Comment by charlesh88** [comment]
Reviewed 10-18-17. Not accepted.

The toolbar UI, while at the top, has elements that now fall below the toolbar for certain tools (like the Text tool) and overlays across the image in a confusing and undesirable way.
![screen shot 2017-10-18 at 3 11 23 pm](https://user-images.githubusercontent.com/1056412/31745259-de902102-b416-11e7-9dce-5e004829db6d.png)

**Comment by dedywahyudi** [comment]
@charlesh88 
So, The width coming from existing toolbar styling of Painterro plugin: https://www.npmjs.com/package/painterro

To avoid the bar moving down, i think we need set minimum width for the modal window that will fits with full mode of the toolbar

cc  @kbowerma: Thoughts?

**Comment by kbowerma** [comment]
can we figure out what the minimum width needs to be and see if it is reasonable?

**Comment by dedywahyudi** [comment]
Yes, the plan is to set specific class that set minimum width for the annotation toolbar.

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
Inputs on toolbar should not overlapping now

**Comment by charlesh88** [comment]
Reviewed 11/07/17, fixed.
