### ISSUE TITLE
[UI] View Large Dialog not displaying "New Notebook Entry" button

### ISSUE THREAD

**Issue by charlesh88** [topcoderinc/openmct#13]
Delivery 10-10-17

Reference Notebook UI v1.0.3 page 136.

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
This is fixed now: 
![screenshot 2017-10-16 12 29 04](https://user-images.githubusercontent.com/4476442/31596582-9ebf7a0a-b26d-11e7-9ad8-36f9eb67e9e3.png)

**Comment by charlesh88** [comment]
Reviewed 10-18-17. Accepted.
