### ISSUE TITLE
[Styles] Message dialogs clipped

### ISSUE THREAD

**Issue by charlesh88** [topcoderinc/openmct#14]
Delivery 10-10-17

Something is causing message dialogs to not display properly and get clipped in small screen resolutions, hiding the action buttons:
![screen shot 2017-10-11 at 11 45 10 am](https://user-images.githubusercontent.com/1056412/31460045-e52e60c0-ae79-11e7-9443-c1ad07d7b339.png)

@charlesh88 has verified that this is unique to the Notebook code fork and can't be duplicated in the main code fork.

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
Delete Confirmation Dialog Fixed now. 

![screenshot 2017-10-16 12 27 27](https://user-images.githubusercontent.com/4476442/31596552-68559756-b26d-11e7-913d-9764105024d9.png)

**Comment by charlesh88** [comment]
Reviewed 10-18-17. Accepted.
