### ISSUE TITLE
[Mobile] Create button displayed

### ISSUE THREAD

**Issue by charlesh88** [topcoderinc/openmct#15]
Delivery 10-10-17

Default mobile styles appear to be being overridden: the Create button is being displayed, but should not. 
![screen shot 2017-10-11 at 11 53 39 am](https://user-images.githubusercontent.com/1056412/31460369-0a3e1440-ae7b-11e7-927d-ae1485cc57c6.png)

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
Default Create Button reverted now

**Comment by charlesh88** [comment]
Reviewed 10-18-17. Accepted.
