### ISSUE TITLE
[Dev] Notebook SCSS files not in the correct place

### ISSUE THREAD

**Issue by charlesh88** [topcoderinc/openmct#16]
Delivery 10-10-17

Notebook CSS styles appear to be placed in the Style Guide SCSS directory path. This is definitely not the right place for these to be held; new SCSS files specific to the Notebook should be within the Notebook plugin directory structure.

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
Notebook css moved to Notebook folder
Please check Code updates: https://github.com/topcoderinc/openmct

**Comment by charlesh88** [comment]
Reviewed 10-18-17. Not accepted.
 
- The main SASS file `/example/notebook/res/sass/_style-guide-base.scss` is including and compiling all of the SASS files also used by the Style Guide. This duplicates many classes across the application, and unnecessarily bloats the CSS. The rendered Notebook CSS should *only* include classes needed for the Notebook, and should be loaded properly with the Notebook plugin so that is loaded after the platforms CSS files.
- While SASS files have been moved, the SASS file name needs to be changed for clarity: `_style-guide-base.scss`. Instead, this should be named something more clear like `_notebook-base.scss`.

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
Ok, clear for the respond.

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
Folder moved, can you please check?

**Comment by charlesh88** [comment]
Reviewed 11-07-17. Not accepted.

The code is still pulling in and duplicating platform class definitions unnecessarily. The culprit is 
https://github.com/topcoderinc/openmct/tree/master/example/notebook/res/sass/notebook-espresso.scss, which doesn't need and should not import the following files: 

`@import "../../../../platform/commonUI/general/res/sass/glyphs`
`@import "../../../../platform/commonUI/general/res/sass/icons`
`@import "../../../../platform/commonUI/general/res/sass/search/search`

Also, a thematic CSS file is being generated for Espresso (https://notebook-openmct.herokuapp.com/example/notebook/res/css/notebook-espresso.css) but should not be: there is nothing that needs to be thematic about the Notebook, base theme styles will do all the work here.

So, I recommend the following:

1. Make changes to fix imports in notebook-espresso.scss as noted above.
2. Rename notebook-espresso.scss to notebook.scss, which will render to notebook.css.
3. Remove notebook-snow.scss.

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma Ok, i'm asking more edits.

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma This should be fixed now. 
Please check the commits: https://github.com/topcoderinc/openmct/pull/26/commits/46d7c117cbf34d3861642d9e548ebc0a9db9f8f0

**Comment by charlesh88** [comment]
Reviewed 11/13/17, fixed.
