### ISSUE TITLE
[UI] Delete Entry dialog text not correct

### ISSUE THREAD

**Issue by charlesh88** [topcoderinc/openmct#21]
10-18-17, during issue fix review.

When deleting a Notebook entry from a Notebook, the resulting dialog text is incorrect:
![screen shot 2017-10-18 at 3 22 20 pm](https://user-images.githubusercontent.com/1056412/31745600-48c6a4c8-b418-11e7-881e-e3081418017c.png)

The message should appear as per Notebook UI v1.0.3 page 138.

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
Ok, clear. I'm asking the edit for this ticket

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
This is fixed now

**Comment by charlesh88** [comment]
Reviewed 11/07/17, fixed.
