### ISSUE TITLE
[UI] Notebook Entry embed links not navigating to live objects

### ISSUE THREAD

**Issue by charlesh88** [topcoderinc/openmct#25]
Per Notebook UI v1.0.3 pg. 127 callout 3, the title of an embedded object in a Notebook entry should be linking to the live object, but is not. The thumbnail *is* correctly linking to the object's snapshot. 

![screen-shot-2017-11-07-at-4 32 18-pm-annotated](https://user-images.githubusercontent.com/1056412/32525544-c806eaa6-c3d9-11e7-9876-804ba2597883.png)

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma Clear. I'll update again later

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma This should be fixed now. 
Please check the commits: https://github.com/topcoderinc/openmct/pull/26/commits/46d7c117cbf34d3861642d9e548ebc0a9db9f8f0

And updated heroku here: https://notebook-openmct.herokuapp.com/

**Comment by charlesh88** [comment]
Reviewed 11/13/17, fixed.
