### ISSUE TITLE
[UI] Markup not correct for scrolling

### ISSUE THREAD

**Issue by charlesh88** [topcoderinc/openmct#3]
Delivery 10-10-17.

Per Notebook UI v1.0.3 page 118 the search bar, controls and new entry area must not be included in the list scrolling region.
![nasa-mct-notebook herokuapp com scroll issue](https://user-images.githubusercontent.com/1056412/31457911-2478588c-ae73-11e7-8e7d-9cc627b1dfda.png)

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
This should be fixed, please check

**Comment by charlesh88** [comment]
Reviewed 10-18-17. Accepted.
