### ISSUE TITLE
[UI] Notebook is manifesting in Edit mode

### ISSUE THREAD

**Issue by charlesh88** [topcoderinc/openmct#4]
Delivery 10-10-17.

The Notebook should never manifest in Edit mode. Creating a Notebook is more akin to creating a Folder: after selecting from the Create menu, the user would interact with a standard dialog initially, with the newly created blank Notebook appearing as shown on Notebook UI v1.0.3 Page 121. I don’t show this dialog in the UI document; if that would be helpful I can easily add and send a revised UI.

There is a related issue: creating a new entry in a Notebook that has been added to a Layout navigates the user away from the Layout and places the Notebook into Edit mode. Per Notebook UI v1.0.3 page 123, this should not be the case.

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
Please check current solution.

**Comment by charlesh88** [comment]
Reviewed 10-18-17. Accepted.
