### ISSUE TITLE
[UI] New entry should display input textarea

### ISSUE THREAD

**Issue by charlesh88** [topcoderinc/openmct#5]
Delivery 10-10-17.

Adding a new entry to a Notebook must display an input textarea and place the user’s cursor in it. Notebook UI v1.0.3 Page 124.

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
I think this fixed, can you check?

**Comment by charlesh88** [comment]
Reviewed 10-18-17. Not accepted.

While this now works properly when clicking the Start area, it doesn't appear and work as desired when dropping an object onto the Start area:
![screen shot 2017-10-18 at 3 24 16 pm](https://user-images.githubusercontent.com/1056412/31745629-70e796d8-b418-11e7-8e21-d30d0d1b17a6.png)

What the UI shows on Notebook UI v1.0.3 page 125 is there should be hint text above the thumbnail that reads "Enter text here" - currently as shown in screenshot above the area is blank above the thumbnail.

On further consideration (and hopefully would be easier to implement at this point) our preference would be for the current fix to this issue to also be applied to the dropped object case as well: when an object is dropped, also display the text input and put the user's cursor into it:
![screen shot 2017-10-18 at 3 27 41 pm](https://user-images.githubusercontent.com/1056412/31745735-eedf2e5c-b418-11e7-8444-95fe3b0ea418.png)

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
Please check the updated code

**Comment by charlesh88** [comment]
Reviewed 11/07/17, fixed. Looks great, thanks!
