### ISSUE TITLE
[UI] Snapshot thumb click should display the Snapshot

### ISSUE THREAD

**Issue by charlesh88** [topcoderinc/openmct#6]
Delivery 10-10-17.

Clicking a Snapshot thumb in an entry should display the Snapshot, same as choosing View Snapshot from the context menu. Notebook UI v1.0.3 Page 127 callout 2.

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
This should be fixed by now.

**Comment by charlesh88** [comment]
Reviewed 10-18-17. Accepted.
