### ISSUE TITLE
[UI] Recent, Shared with Me, etc. should not be present

### ISSUE THREAD

**Issue by charlesh88** [topcoderinc/openmct#7]
Delivery 10-10-17.

The developer has added a Recent, Shared with Me, etc. at the bottom of the tree. While these are shown in the UI doc, this is not part of the Notebook and should be removed.

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
Bottom area of the tree just removed. 

![screenshot 2017-10-16 12 34 02](https://user-images.githubusercontent.com/4476442/31596691-5cd84576-b26e-11e7-858d-021102045602.png)

**Comment by charlesh88** [comment]
Reviewed 10-18-17. Accepted.
