### ISSUE TITLE
[Performance] Loading issues

### ISSUE THREAD

**Issue by charlesh88** [topcoderinc/openmct#8]
Delivery 10-10-17.

- When just going to the root URL `http://nasa-mct-notebook.herokuapp.com/` the app sometimes takes a very long time to load in my iPhone 6 and in Chrome’s desktop browser mobile emulation. -
- When trying to go to a URL that includes an address for a Notebook (like `http://nasa-mct-notebook.herokuapp.com/#/browse/mine/7dc94eb3-406f-4a19-ba28-2019ce1e331d?tc.mode=local&tc.timeSystem=utc&tc.startDelta=1800000&tc.endDelta=0&view=notebook.view`), it sometimes never loads and throws this error:
![screen shot 2017-10-11 at 11 08 35 am](https://user-images.githubusercontent.com/1056412/31458315-96e5d376-ae74-11e7-84b1-f7a5d99df44c.png)

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
This error should not exists again, please check.

**Comment by charlesh88** [comment]
Reviewed 10-18-17. Accepted.
